[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[env]
# Allow esp-hal to run on ESP32 v1.0 chips (default minimum is v3.0)
ESP_HAL_CONFIG_MIN_CHIP_REVISION = "100"

[build]
target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core"]
