[package]
name = "firmware"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-bootloader-esp-idf = { version = "0.6", features = ["esp32"] }
esp-hal = { version = "1.2", features = ["esp32", "unstable"] }
esp-backtrace = { version = "0.20", features = ["esp32", "panic-handler", "println"] }
esp-println = { version = "0.18", features = ["esp32", "uart"], default-features = false }
esp-hal-smartled = { version = "0.18", features = ["esp32"] }
smart-leds = "0.4"
